"""YouTube 登录并导出 yt-dlp 能用的 cookies 文件。

为什么需要它：YouTube 现在对匿名请求做「Sign in to confirm you're not a bot」风控，
报错原文让你用 --cookies-from-browser 或 --cookies。实测这台机器上两条路都不通：

  - --cookies-from-browser chrome/edge/brave  → 找不到 cookies 数据库（用户用的是 Arc）
  - --cookies-from-browser safari             → macOS 沙箱拒绝读取（需要完全磁盘访问权限）
  - 换 player_client（tv/web_safari/mweb/ios）→ 风控那关确实过了，但 YouTube 只回
    分镜图（sb0~sb3），拿不到任何音视频格式，等于没用

所以最省事、且不依赖用户装插件或改系统权限的做法，是让本应用自己开一个浏览器窗口
让用户登录一次，然后把登录态导出成 Netscape 格式的 cookies.txt 交给 yt-dlp。
这与抖音那边「打开浏览器扫码登录并保存登录态」是同一套思路。

导出后还会用一次真实解析来验证 cookies 是否真的能过风控——否则用户以为配好了，
下一次任务才发现还是失败。
"""

from __future__ import annotations

import asyncio
import logging
import time
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path

logger = logging.getLogger(__name__)

# 登录判定用的 cookie。Google 登录后一定会下发这几个，且都是 HttpOnly 的长效 cookie，
# 比「页面上有没有头像」更稳定（头像选择器会随页面改版而变）。
_LOGIN_COOKIE_NAMES = ("SAPISID", "__Secure-1PSID", "__Secure-3PSID", "LOGIN_INFO")

# Netscape cookies.txt 的文件头。yt-dlp 用 http.cookiejar.MozillaCookieJar 解析，
# 缺了这行会被当成无效文件。
_NETSCAPE_HEADER = (
    "# Netscape HTTP Cookie File\n"
    "# This file was generated by Spark Video Tools for yt-dlp. Do not edit.\n"
    "\n"
)


@dataclass
class YouTubeLoginSession:
    """供 API 轮询的登录会话状态。"""

    status: str = "idle"        # idle / waiting / success / failed
    message: str = ""
    started_at: datetime | None = None
    finished_at: datetime | None = None
    cookies_path: str = ""
    state_path: str = ""
    cookie_count: int = 0
    verify_message: str = ""
    verified: bool | None = None
    _task: asyncio.Task | None = field(default=None, repr=False)

    def running(self) -> bool:
        return self._task is not None and not self._task.done()

    def snapshot(self) -> dict:
        return {
            "status": self.status,
            "message": self.message,
            "running": self.running(),
            "started_at": self.started_at.isoformat() if self.started_at else None,
            "finished_at": self.finished_at.isoformat() if self.finished_at else None,
            "cookies_path": self.cookies_path,
            "state_path": self.state_path,
            "cookie_count": self.cookie_count,
            "verify_message": self.verify_message,
            "verified": self.verified,
        }


def to_netscape(cookies: list[dict]) -> str:
    """把 Playwright 的 cookie 列表转成 Netscape cookies.txt。

    格式为制表符分隔的 7 列：
        domain  includeSubdomains  path  secure  expires  name  value

    两个容易写错的点：
      - HttpOnly 的 cookie 必须给域名加 `#HttpOnly_` 前缀，否则 MozillaCookieJar
        解析时会丢弃它们——而 Google 的关键登录 cookie 恰恰都是 HttpOnly；
      - 会话 cookie（expires 为 -1）要写成 0，不能写 -1，否则部分解析器直接判为过期。
    """
    lines = [_NETSCAPE_HEADER.rstrip("\n") + "\n"]
    for cookie in cookies:
        domain = str(cookie.get("domain") or "")
        if not domain:
            continue
        name = str(cookie.get("name") or "")
        if not name:
            continue
        value = str(cookie.get("value") or "")
        expires = cookie.get("expires")
        try:
            expiry = int(float(expires))
        except (TypeError, ValueError):
            expiry = 0
        if expiry <= 0:
            expiry = 0
        prefix = "#HttpOnly_" if cookie.get("httpOnly") else ""
        fields = [
            f"{prefix}{domain}",
            "TRUE" if domain.startswith(".") else "FALSE",
            str(cookie.get("path") or "/"),
            "TRUE" if cookie.get("secure") else "FALSE",
            str(expiry),
            name,
            value,
        ]
        lines.append("\t".join(fields) + "\n")
    return "".join(lines)


def login_cookie_count(cookies: list[dict]) -> int:
    """命中登录判定的 cookie 个数（>=1 视为已登录）。"""
    names = {str(c.get("name") or "") for c in cookies}
    return sum(1 for want in _LOGIN_COOKIE_NAMES if want in names)


async def export_cookies(state_path: Path, cookies_path: Path) -> int:
    """把 Playwright storage_state 里的 cookie 转写为 Netscape cookies.txt。

    返回写入的 cookie 条数。
    """
    import json

    data = json.loads(Path(state_path).read_text(encoding="utf-8"))
    cookies = data.get("cookies") or []
    cookies_path.parent.mkdir(parents=True, exist_ok=True)
    cookies_path.write_text(to_netscape(cookies), encoding="utf-8")
    return len(cookies)


async def verify_cookies(cookies_path: Path, *, video_url: str, timeout: float = 120) -> tuple[bool, str]:
    """用一次真实解析验证 cookies 是否真的能过风控。

    只看「文件里有 cookie」是不够的：cookie 可能是过期的、或者只含广告追踪 cookie。
    真正能说明问题的只有 yt-dlp 拿它去解析一次。
    """
    import sys

    if not cookies_path.exists():
        return False, "cookies 文件不存在"

    def run() -> tuple[int, str]:
        import subprocess

        result = subprocess.run(
            [
                sys.executable, "-m", "yt_dlp",
                "--simulate", "--no-warnings", "--socket-timeout", "20",
                "--cookies", str(cookies_path),
                video_url,
            ],
            capture_output=True,
            text=True,
            timeout=timeout,
        )
        return result.returncode, (result.stdout + result.stderr).strip()

    try:
        code, output = await asyncio.to_thread(run)
    except Exception as exc:  # noqa: BLE001 - 验证失败不该让登录流程崩掉
        return False, f"验证时出错：{type(exc).__name__}: {exc}"

    if code == 0:
        return True, "验证通过：cookies 可用，匿名风控已绕过"

    tail = output.splitlines()[-1] if output else "无输出"
    if "Sign in to confirm" in output:
        return False, f"验证未通过：仍然要求登录（{tail[:160]}）"
    return False, f"验证未通过：{tail[:200]}"


class YouTubeAuthManager:
    """管理 YouTube 登录会话：一次只允许一个会话。"""

    def __init__(self) -> None:
        self.session = YouTubeLoginSession()

    async def start_login(
        self,
        state_path: Path,
        cookies_path: Path,
        *,
        timeout: int = 300,
        probe_url: str = "https://www.youtube.com/watch?v=EN7frwQIbKc",
    ) -> YouTubeLoginSession:
        if self.session.running():
            return self.session
        self.session = YouTubeLoginSession(
            status="waiting", message="已打开浏览器，请在窗口里登录 Google 账号…",
            started_at=datetime.now(),
        )
        self.session._task = asyncio.create_task(
            self._login_worker(state_path, cookies_path, timeout, probe_url)
        )
        return self.session

    async def _login_worker(
        self, state_path: Path, cookies_path: Path, timeout: int, probe_url: str
    ) -> None:
        session = self.session
        try:
            # 复用抖音那边的浏览器启动配置（patchright + stealth 脚本 + chromium channel）。
            # 这样做不只是省代码：YouTube 同样会做自动化检测，用同一套已验证能够
            # 正常打开页面的反检测配置，比另起一套默认 Playwright 靠谱得多。
            # 惰性导入：patchright/Playwright 是可选依赖，不能在模块导入期就要求它存在。
            from app.providers.publisher.douyin import _new_context, _require_playwright

            async_playwright = _require_playwright()
            async with async_playwright() as playwright:
                browser, context = await _new_context(playwright, None, headless=False)
                try:
                    page = await context.new_page()
                    await page.goto(
                        "https://www.youtube.com/", wait_until="domcontentloaded", timeout=90000
                    )
                    deadline = asyncio.get_running_loop().time() + timeout
                    logged_in = False
                    while asyncio.get_running_loop().time() < deadline:
                        cookies = await context.cookies()
                        if login_cookie_count(cookies) > 0:
                            logged_in = True
                            break
                        await page.wait_for_timeout(2000)

                    if not logged_in:
                        session.status = "failed"
                        session.message = f"登录超时（{timeout}s），没有检测到 Google 登录态，请重试"
                        session.finished_at = datetime.now()
                        return

                    state_path.parent.mkdir(parents=True, exist_ok=True)
                    await context.storage_state(path=str(state_path))
                finally:
                    await context.close()
                    await browser.close()

            session.state_path = str(state_path)
            count = await export_cookies(state_path, cookies_path)
            session.cookies_path = str(cookies_path)
            session.cookie_count = count

            session.message = f"登录成功，已导出 {count} 条 cookie，正在验证…"
            ok, detail = await verify_cookies(cookies_path, video_url=probe_url)
            session.verified = ok
            session.verify_message = detail
            session.status = "success" if ok else "failed"
            session.message = (
                f"登录成功，已导出 {count} 条 cookie；{detail}"
                if ok
                else f"登录成功并已导出 cookie，但{detail}"
            )
            session.finished_at = datetime.now()
        except Exception as exc:  # noqa: BLE001
            logger.exception("YouTube 登录失败")
            session.status = "failed"
            session.message = f"登录失败：{type(exc).__name__}: {exc}"
            session.finished_at = datetime.now()

    async def check(self, cookies_path: Path, *, probe_url: str) -> tuple[bool, str]:
        """对已有的 cookies 文件做一次验证（不重新登录）。"""
        started = time.monotonic()
        ok, detail = await verify_cookies(cookies_path, video_url=probe_url)
        return ok, f"{detail}（耗时 {time.monotonic() - started:.0f}s）"


auth_manager = YouTubeAuthManager()
